### ISSUE TITLE
Error in all samples INITVFP2C32(VFP2C_INIT_ALL) not Found

### ISSUE THREAD

**Issue by tomkn** [ChristianEhlscheid/vfp2c32#1]
Hello,
congratulations to the fine tool !

I open the example project and start one of the programs, for example dialog.prg.
I get an error on line INITVFP2C32(VFP2C_INIT_ALL) : 'initvfp2c32.prg' not found.
If I click ignore, programs work.

Thanks for help
Tom

**Comment by ChristianEhlscheid** [comment]
This issue should finally be resolved in the latest version ...
