### ISSUE TITLE
InitVFP2C32

### ISSUE THREAD

**Issue by CHamlinPNP** [ChristianEhlscheid/vfp2c32#13]
I am trying to build my projects...I make sure that VFP2C32.fll is listed under API libraries. But when I build the project it keeps choking on the call to INITVFP2C32 function. It keeps asking me to locate it...I keep pointing it to the VFP2C32.fll but it is still listed in the .ERR file and it does not remember what I selected.

What am I doing wrong?

**Comment by jhernancanom** [comment]
Hi, friends.
I am running the script shown in the image, with several VFP2C32.FLLs have found in my computer.

But I am getting a related msg error (as Chamlin says in this thread) but **_only_** with the last version 2021-08-09 .

![image](https://user-images.githubusercontent.com/5818845/170883496-8d5a978b-4d0c-40d8-b752-cf5e1d3832cf.png)

![image](https://user-images.githubusercontent.com/5818845/170883628-4f5cda1a-8e26-42e8-a265-9ee4e960dfa1.png)

**Comment by ChristianEhlscheid** [comment]
Hello,
the function "INITVFP2C32" was deprecated years ago, it's not needed anymore, i've rewritten the library so every library function 
that uses a C function from a C dll that might not be available on the target operating system will initialize itself on the first use automatically.

As for using VFP with SQLLite - this script seems to be too much of a hassle in my opinion, 
I've tried the open source ODBC driver for SQLLite (http://www.ch-werner.de/sqliteodbc/) and that seems to work 
fine with VFP, so one can just use the regular functions for remote data access - SQLCONNECT, SQLEXEC or CursorAdapter classes.

**Comment by jhernancanom** [comment]
Yes, Christian: you are right with respect to SQLiteODBC (from Ch. Werner).

But the importance of the solution shown including SQLITE3.DLL (and VFP2C32.DLL) is that SQLITE3.dll does not need to be registered: just DECLAREd, but --for being able to "receive" the info-- we need VFP2C32.DLL in the way shown in the script.

And the problem with "registering" is the elevation (run as admin).

If you can help us with this (registering and/or elevation), we will be glad.

Thanks for clarifying about INITVFP2C32.

**Comment by CHamlinPNP** [comment]
I have no problem if “InitVFP2C32” has been deprecated…however the documentation still tells users to use it. When first starting to use the library the documentation is key…yet in this case it is telling you something that is not needed (and is no longer functional without receiving an error) should be updated. Because InitVFP2C32 appears to give everyone a problem…why not just remove it at this point?

-Curt
