### ISSUE TITLE
Easier way to access specific functionality

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#16]
I oppose any kind of library because they are often junk drawers of unrelated content. Grouping of functionality is unlike FoxPro itself. This grouping of functionality is only possibly of use as you are programming, and not really necessary or beneficial to the application while running. In order to use the SUM() function in straight FoxPro, I do not first have to SET PROCEDURE TO Math.

FoxPro allows extending its functionality in a more natural way than libraries and that is by the lowly separate .PRG file.

For example, to use the ADIREX function of vfp2c32 immediately and without first issuing SET LIBRARY or #INCLUDE vfp2c.h throughout your application, create an ADIREX.PRG in your folder of .prg files with this content:

```
LPARAMETERS tcCursorName, tcFilePattern, tnFileAttribs, tnDestType
IF NOT "VFP2C32" $ SET('LIBRARY')
  SET LIBRARY TO VFP2C32.FLL ADDITIVE
ENDIF
RETURN ADIREX(m.tcCursorName, m.tcFilePattern, m.tnFileAttribs, m.tnDestType)

```
ADIREX requires numeric file attributes, instead of the character file attributes already known by ADIR users. To get around that create a program called GetADirExAttribs.PRG in your folder of .prg files with the following content. The BITXOR is used in case the user enters duplicates of the RASHD attributes.

```
LPARAMETERS m.tcAttributes
#INCLUDE vfp2c.h

LOCAL m.lcAttributes, m.lnAttributes, m.lnPos, m.lcAttr
m.lcAttributes = IIF(VARTYPE(m.tcAttributes) = "C", UPPER(m.tcAttributes), "")

m.lnAttributes = 0

FOR m.lnPos = 1 TO LEN(m.lcAttributes)
    m.lcAttr = SUBSTR(m.lcAttributes, m.lnPos, 1)

    DO CASE
        CASE m.lcAttr = "R"
            m.lnAttributes = BITXOR(m.lnAttributes, FILE_ATTRIBUTE_READONLY)
        CASE m.lcAttr = "A"
            m.lnAttributes = BITXOR(m.lnAttributes, FILE_ATTRIBUTE_ARCHIVE)
        CASE m.lcAttr = "S"
            m.lnAttributes = BITXOR(m.lnAttributes, FILE_ATTRIBUTE_SYSTEM)
        CASE m.lcAttr = "H"
            m.lnAttributes = BITXOR(m.lnAttributes, FILE_ATTRIBUTE_HIDDEN)
        CASE m.lcAttr = "D"
            m.lnAttributes = BITXOR(m.lnAttributes, FILE_ATTRIBUTE_DIRECTORY)
        CASE m.lcAttr = "F"
            m.lnAttributes = BITXOR(m.lnAttributes, FILE_ATTRIBUTE_FAKEDIRECTORY)
        CASE m.lcAttr = "C"
            m.lnAttributes = BITXOR(m.lnAttributes, FILE_ATTRIBUTE_COMPRESSED)
        OTHERWISE
            * Handle unrecognized or custom attribute values here
            * You can choose to ignore or handle them accordingly
    ENDCASE
ENDFOR

RETURN m.lnAttributes

```
You will also need GetADirExDestType.prg

```
#INCLUDE vfp2c.h
LPARAMETERS tnDestType
DO CASE
    CASE UPPER(tnDestType) = "ARRAY"
        RETURN ADIREX_DEST_ARRAY
    CASE UPPER(tnDestType) = "CURSOR"
        RETURN ADIREX_DEST_CURSOR
    OTHERWISE
        RETURN -1  && Invalid destination type
ENDCASE
```

You might also want to use GetADirExFilterFlag.prg
```
LPARAMETERS tcFilterType
#include vfp2c.h
DO CASE
    CASE UPPER(m.tcFilterType) = "ALL"
        RETURN ADIREX_FILTER_ALL
    CASE UPPER(m.tcFilterType) = "NONE"
        RETURN ADIREX_FILTER_NONE
    CASE UPPER(m.tcFilterType) = "EXACT"
        RETURN ADIREX_FILTER_EXACT
    CASE UPPER(m.tcFilterType) = "ANY"
        RETURN 0  && Default filter flag (no filter)
    OTHERWISE
        RETURN -1  && Invalid filter type
ENDCASE

```
Then if you want to use ADIREX in your application, just use it as you would any other part of FoxPro.

```
?ADIREX(;
	'c_mycursor',;
	'c:\somefolder\somefiles.*',;
	GetADirExAttribs("RASHDSHDAR"),;
	GetADirExDestType("CURSOR") + GetADirExFilterFlag('ANY');
	 )

```

**Comment by myearwood1** [comment]
Then, having the above, it takes very little time to create a superior DirX, which is a better name than ADIR<whatever> since ADirEx does not only make an array but the far more useful Cursor.

DIR is a FoxPro command that can list filenames or the number of records in specified tables. That command is the one that needed to be enhanced to allow for producing a cursor of files or an array. In earlier versions of Fox, you could not create a really large array. So, with DirX you can create an array if you are using VFP9. You can also create a cursor of well over 100,000 files.

Furthermore, you get source code you can use and modify without having to rely on some C programmer.

This is how I should have done a recursive ADIR in the first place. Place this in your folder of Programs as DIRX.PRG

You can create an array
dimension laTest[1]
?dirx(@laTest,'c:\somefolder\*.txt','RASHD',.T.)

or you can create a cursor
?dirx('c_mycurs','c:\somefolder\*.*',"RASHD",.T.)

DIRX.PRG
```
LPARAMETERS tuDestinationName, tcPattern, tcAttributes, tlRecurse

IF vartype(m.tcAttributes)<>"C"
	tcAttributes = ""
endif
*Default to RA
if not "R"$m.tcAttributes
    tcAttributes = "R" + m.tcAttributes
ENDIF
if not "A"$m.tcAttributes
    tcAttributes = left(m.tcAttributes,1)+"A"+substr(m.tcAttributes,2)
ENDIF

LOCAL lcTempCursorFinal, lcPattern, lnAttributes, lnReturn, lnR, lnA, lnS, lnH, lnD

lnAttributes = GetADirExAttribs(m.tcAttributes)

if vartype(m.tcPattern)<>"C"
	lcPattern = ""
endif
lcPattern = m.tcPattern

lcTempCursorFinal = SYS(2015)
CREATE CURSOR (m.lcTempCursorFinal) (filename C(254), modified T, filesize N(20,0), records I, fileattribs i, cfileattribs C(5), lReadOnly L, lArchive L, lHidden L, lSystem L, lDirectory L, folder C(254))

lnReturn = RecurseFolders(m.lcTempCursorFinal, m.lcPattern, m.lnAttributes, m.tlRecurse)

*Do all of these here rather than throughout the processing
lnR = GetADirExAttribs("R")
lnA = GetADirExAttribs("A")
lnS = GetADirExAttribs("S")
lnH = GetADirExAttribs("H")
lnD = GetADirExAttribs("D")

replace all ;
	lReadOnly with BitAnd(FileAttribs,m.lnR)=m.lnR, ;
	lArchive with BitAnd(FileAttribs,m.lnA)=m.lnA, ;
	lSystem with BitAnd(FileAttribs,m.lnS)=m.lnS, ;
	lHidden with BitAnd(FileAttribs,m.lnH)=m.lnH, ;
	lDirectory with BitAnd(FileAttribs,m.lnD)=m.lnD, ;
	cfileattribs with ;
		IIF(lReadonly,"R","")+;
		IIF(lArchive,"A","")+;
		IIF(lSystem,"S","")+;
		IIF(lHidden,"H","")+;
		IIF(lDirectory,"D","")

DO CASE
    CASE type("alen(m.tuDestinationName)") = 'N' && Array
    	COPY TO ARRAY laTemp
    	acopy(laTemp,tuDestinationName,1,-1,1)
	OTHERWISE
		USE IN SELECT(m.tuDestinationName)
		SELECT 0
		USE dbf(m.lcTempCursorFinal) AGAIN ALIAS (m.tuDestinationName)
endcase
use in (m.lcTempCursorFinal)
RETURN m.lnReturn

PROCEDURE RecurseFolders(tcDestination, tcPattern, tnAttributes, m.tlRecurse)
    LOCAL lcTempCursorFiles, lcTempCursorFolders, lcPattern, lnSelect, lnReturn

	lnSelect = select()
	
    lcTempCursorFiles = SYS(2015)
	lcPattern = justfname(m.tcPattern)

    lnReturn = 0

    CREATE CURSOR (m.lcTempCursorFiles) (filename C(254), dosfilename C(13), creationtime T, accesstime T, writetime T, filesize N(20,0), fileattribs I, Folder c(254))
	
    IF ADIREx(m.lcTempCursorFiles, m.tcPattern, m.tnAttributes, GetADirExDestType("CURSOR") + GetADirExFilterFlag("ANY")) > 0

		replace all folder with justpath(m.tcPattern)

    	lnReturn = ProcessFiles(m.lcTempCursorFiles,m.tcDestination,m.lcPattern)

	    IF m.tlRecurse
		    lcTempCursorFolders = SYS(2015)
		    lnAttrib = GetADirExAttribs("D")

		    select ;
		    	filename, ;
		    	folder ;
		    from (m.lcTempCursorFiles) ;
			where ;
				bitand(fileattribs,m.lnAttrib) = m.lnAttrib ;
			    and not inlist(alltrim(filename),".","..") ;
		    into cursor (m.lcTempCursorFolders) nofilter

		    SCAN
		        lnReturn = m.lnReturn + RecurseFolders(m.tcDestination,addbs(alltrim(folder))+addbs(alltrim(filename))+m.lcPattern,m.tnAttributes,m.tlRecurse)
		    ENDSCAN

		    USE IN (SELECT(m.lcTempCursorFolders))

		endif
    endif

    USE IN (SELECT(m.lcTempCursorFiles))
    
    select (m.lnSelect)
    
    RETURN m.lnReturn
    
ENDPROC

PROCEDURE ProcessFiles(tcSource, tcDestination, tcPattern)

    local lcTempCursorFiles, lnAttrib, lnSelect, lnReturn
    lnSelect = select()

    lcTempCursorFiles = SYS(2015)
    lnAttrib = GetADirExAttribs("D")

    SELECT *, ;
    	writetime as Modified ;
    FROM (m.tcSource) ;
    where ;
	    (bitand(fileattribs,m.lnAttrib) <> m.lnAttrib ;
	    or inlist(alltrim(filename),".","..")) ;
    into cursor (m.lcTempCursorFiles) nofilter

	lnReturn = reccount(m.lcTempCursorFiles)
	if m.lnReturn > 0

	    select (m.tcDestination)
	    APPEND FROM dbf(m.lcTempCursorFiles)

	endif

    USE IN (SELECT(m.lcTempCursorFiles))

	select (m.lnSelect)

    RETURN m.lnReturn
ENDPROC
```

**Comment by EnsignRho** [comment]
Thank you for your contribution, Mike!
As always... helping the community with your kindness, generosity, and love for the people.

**Comment by SeregaKR** [comment]
I just have one question. Should we be using: 
` SET LIBRARY TO VFP2C32.FLL`
without "ADDITIVE" ? I'm frankly curious because I have some problems without it when using two libraries for one of the forms.

**Comment by ChristianEhlscheid** [comment]
I am willing to alter the ADIREX function to alternativly accept the character type arguments, 
so you can at least get rid of the GetADirExAttribs, GetADirExDestType (which contains an error by the way, there is no ADIREX_DEST_VARIABLE - the third option besides an array or a cursor is ADIREX_DEST_CALLBACK) and GetADirExFilterFlags.

**Comment by SeregaKR** [comment]
> I always use ADDITIVE, otherwise all prior loaded libraries are unloaded.
> 
> SET LIBRARY TO vfp2c32.fll ?SET('Library') SET LIBRARY TO someother.fll ?SET('Library')

I was talking about this code:
```
LPARAMETERS tcCursorName, tcFilePattern, tnFileAttribs, tnDestType
IF NOT "VFP2C32" $ SET('LIBRARY')
  SET LIBRARY TO VFP2C32.FLL
ENDIF
RETURN ADIREX(m.tcCursorName, m.tcFilePattern, m.tnFileAttribs, m.tnDestType)
```

**Comment by ChristianEhlscheid** [comment]
The same applies, if you use multiple FLL's in your application always use ADDITIVE, otherwise you might unintentionally unload libraries.

**Comment by myearwood1** [comment]
Yes. Always use ADDITIVE. Simple mistake. I already have a udf that accepts
the fll name.

I would appreciate not having to litter my app with #include to use any
library.

New programmers can use your library more easily with the ADIREX.PRG.
Commenting can be added in there to explain the parameters without having
to open a help file.

ADir was a mistake in my opinion. FoxPro has super powers to work with
cursors.

I needed this so I can find any newer reports in an app with over 4800 fr?
files.

I am creating DirX to extend the Directory command to output any result.

Thanks

**Comment by myearwood1** [comment]
> Thank you for your contribution, Mike! As always... helping the community with your kindness, generosity, and love for the people.

This is an insulting false thanks. I suffered years of abuse from others. When I finally stand up for myself, the others who did nothing get offended. I will only show respect to those that deserve it.

When I post something it is not for those who think they know it all, but as an alternative for those who really need help.

**Comment by ChristianEhlscheid** [comment]
Hello,

i'm sorry to hear about that, english is not my first language and I misunderstood who you were addressing in some of your messages.

I think you have already found the answers to your questions yourself considering the new issue you opened.
I'll close this one and we can further communicate in the new thread.

**Comment by myearwood1** [comment]
Please have Ensign Rho remove his rude, insulting, and completely sarcastic "thanks" above, or leave my comment here so others can see his true character.

**Comment by EnsignRho** [comment]
Christian, Mike has been banned from forums because of his demeaning rhetoric.  He's found an advocate in you.  Be mindful of his toxic nature.  By his own admission, even his closest colleagues don't include him in things.  I was thinking today he must have a medical condition which causes him to be so negative.

I bent over backwards to address a request he had for ADirEx().  I offered my skills and time for free.  He's particularly hateful to me because I'm a Christian, hence his constant attacks of all things I say or do.

You cannot even find his posts on TekTips because he was so toxic they removed them all.  The only references are the parts people quoted which remain.

Just FYI.
