### ISSUE TITLE
DOS DIR can filter files that do not have an attribute

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#18]
What DOS can do that we cannot is DIR reports\*.frx /A-R which returns a list of all frx files with readonly OFF.

This would be a nice thing to have.

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

I just implemented this.

**Comment by ChristianEhlscheid** [comment]
Hello,

I've reuploaded the 2.0.0.25 release. A bug in the processing of the filtering arguments slipped in.

**Comment by myearwood1** [comment]
You, sir, are the kind of programmer I enjoy working with.

**Comment by myearwood1** [comment]
Hi Christian
I found a little snag. The CHM refers to ADIREX_FILEATTRIBUTES_STRING, but the .h file has ADIREX_STRING_FILEATTRIBUTES

**Comment by myearwood1** [comment]
It also appears the cFileAttributes field name is no longer supported. I am not troubled by it, since I have the GetADirExcAttributes.PRG.

**Comment by ChristianEhlscheid** [comment]
Hello,

Thanks for your feedback, I will correct the help file.

Can you clarify what you meant by "cFileAttributes" field name?
The fieldname for the file attributes converted to a string is "cfileattribs".

**Comment by myearwood1** [comment]
My mistake! I created the table in advance but did not change the data type of the fileattribs column to C(5). Gave a data type mismatch. It's fine now. Thanks!

**Comment by ChristianEhlscheid** [comment]
Hello,

no problem, just be aware that if you use a C(5) column there is the potential chance to run into a column overflow situation if there are more than 5 file attributes set, this should rarely if ever happen in pratice though.

**Comment by myearwood1** [comment]
Would you create a set of single character attributes with their corresponding attribute name in your .h file? 

You have FILE_ATTRIBUTE_READONLY 0x00000001

Could you make a set like these?
FILE_ATTRIBUTE_R        FILE_ATTRIBUTE_READONLY
FILE_ATTRIBUTE_H       FILE_ATTRIBUTE_HIDDEN

My thinking is to extract these from the .h file. When the user gives me R, I could use those to get the long name of the attribute. I ask so you don't have to change SetFileAttributes to handle the single letters. 

Maybe you can use these values too?

What seems to be the full list of single letters are here: 

https://en.wikipedia.org/wiki/File_attribute#:~:text=Reparse%20Point%20(L)%3A%20The,partially%20empty%20and%20non%2Dcontiguous.

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

i've enhanced all file related functions that deal with file attributes to either return or accept the attributes also 
in stringified form, i think this makes it more consistent.

I've also changed two attribute letters so they match the default windows behaviour.

**Comment by myearwood1** [comment]
Fantastic! It is great to work with someone that is capable and anticipates the need.
