### ISSUE TITLE
Missing #ENDIF

### ISSUE THREAD

**Issue by GerhardSc** [ChristianEhlscheid/vfp2c32#2]
Just downloaded and tried to implement it in my app like

  #INCLUDE VFP2C32.H
  SET LIBRARY TO (cDir  + 'VFP2C32.FLL') ADDITIVE

When trying to close the procedure I get the error  "Missing #ENDIF".

The error doesn't show if I comment out the line 
  #INCLUDE VFP2C32.H.

But doing so gives a compile error "Unable to find Unknown SQLEXECEX.

I would love to use your FLL. Could you do something about that error?

TIA
Gerhard Schmidbauer

**Comment by ChristianEhlscheid** [comment]
Hello Gerhard,

it's not ovious what's the issue here, I've checked the header file vfp2c.h and it is fine.
The problem "Unable to find Unknown SQL..." is probably because you have not added the fll itself to the project (in the project window under section "API Libraries").

Regards
Christian

**Comment by GerhardSc** [comment]
Hello Christian,

Thank you for the quick help.
I really did not add the FLL to API Libraries. Sorry!!!
Now that I added it I get no longer an error.

Thank you!
Gerhard
