### ISSUE TITLE
Problem with CTL32 and current release of VFP2C32.FLL

### ISSUE THREAD

**Issue by CHamlinPNP** [ChristianEhlscheid/vfp2c32#20]
Using CTL32...specifically the progress bar...with version of Vfp2C32 2.0.0.19 the createcallbackfunc using 5 parameters worked fine. With Vfp2C32 2.0.0.28 it creates an error.

The line of code is: This._CallbackProcAddress = CREATECALLBACKFUNC("_CallbackProc", "INTEGER","INTEGER,INTEGER,INTEGER,INTEGER", This, 1)

There is a prior call in status bar of only 4 parameters which worked, but this call in progress bar with 5 parameters creates an error.

Like I said at the beginning...it work in 2.0.0.19 but no longer works with 2.0.0.28.

Let me know if you need any further information

![2023-07-29_16-17-58](https://github.com/ChristianEhlscheid/vfp2c32/assets/34104227/0f9d7c24-3ba2-49c7-a023-11f2c9f99f50)

**Comment by CHamlinPNP** [comment]
If it helps...I found a version 2.0.0.24 and it also did not work. So something happened to it between 2.0.0.19 and 2.0.0.24. Hope this helps.

**Comment by ChristianEhlscheid** [comment]
Hello,

thanks you for the bug report, this issue is fixed in the new release 2.0.0.29.
