### ISSUE TITLE
ER: In DOS Attrib command +R -R affects only Readonly.

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#21]
1 - In DOS, the attrib command accepts +R to set the Readonly and -R to remove it. That way I can flip just one attribute.

2 - This is more of a nice-to-have, but DOS Attrib also has /S to recurse the folders.

**Comment by myearwood1** [comment]
This also allows me to flip certain attributes while leaving the rest.

SetFileAttributes(CHRTRAN(getfileattributes("c:\somefolder\testthis.txt",.T.),"R",""))

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

I've improved the function SetFileAttributes so it accepts a string like '+R-A'.
I also added a new function SetFileAttributesEx which works on a wildcard like ADirEx.

Regards
Christian

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

unfortunatly the new SetFileAttributesEx function is broken, I'am working on it and release a working version soon.

**Comment by myearwood1** [comment]
You are a great developer. I look forward to seeing it. Thanks
