### ISSUE TITLE
Error: No table is open in the current work area.

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#22]
Hi Christian

I am using vfp2c32.fll dated 2023-08-01. 
set library to c:\cj_sa_common\progs\vfp2c32.fll
?adirex("c_temp","c:\vfptemp\test.txt","",128+2+512,0,'filename, filesize, writetime') which works.

However snag 1
use in (select("c_temp"))
?adirex("c_temp","c:\vfptemp\test.txt","",128+2+512,0,'filename, filesize, writetime, cfileattribs')

gives me the error No table is open in the current work area.

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

I can reproduce the error when reusing (not closeing) the cursor.
If you want to reuse the cursor (to append another search into it) please make sure you specify the same fields,
otherwise make sure the cursor non existend.

**Comment by myearwood1** [comment]
I was incorrect. I had discovered that and realized my mistake.
