### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#23]
Hi Christian 

I am using vfp2c32.fll dated 2023-08-01. 
set library to c:\cj_sa_common\progs\vfp2c32.fll
?adirex("c_temp","c:\vfptemp\test.txt","",128+2+512,0,'filename, filesize, writetime') which works.

However, ?adirex("c_temp","c:\autoexec.bat","",128+2+512,0,'filename, filesize, writetime')

Returns a cursor with c:\autoexec.bat, but then gives the error Access is denied.

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

the second call searches the whole C drive for an "autoexec.bat", 
when recusing into folders with insufficient rights the error "access denifed" was incorrectly raised.

I've corrected this in the new version, thanks for the report.

**Comment by myearwood1** [comment]
Confirmed. Works, just does not show the file that it could not access.
