### ISSUE TITLE
Run adirex twice, closing cursor in between, added cfileattribs. Error: Function argument value, type or count is invalid.

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#24]
Hi Christian

I am running the following code. It works in vfp9, but we are stuck with vfp6, unfortunately, and it does not work in 6. 

![image](https://github.com/ChristianEhlscheid/vfp2c32/assets/5750619/1922779d-b808-427f-82a3-73f60d779b48)

Hopefully you can think of a solution.

Thanks

**Comment by myearwood1** [comment]
Further info - this was working in VFP 6 for a time.

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

thank you for the report, this issue is resolved in the new version 2.0.0.34.

**Comment by myearwood1** [comment]
Confirmed. Works perfectly.
