### ISSUE TITLE
SqlExecEx with SQLEXECEX_REUSE_CURSOR with error

### ISSUE THREAD

**Issue by zdenekkrejci** [ChristianEhlscheid/vfp2c32#25]
Hallo,
I'm testing sqlExecEx with this code according to Your example:

`
#INCLUDE vfp2c.h

CD (FULLPATH(JUSTPATH(SYS(16))))

IF TYPE('_WIN64') = 'L' AND _WIN64
SET LIBRARY TO vfp2c64.fll ADDITIVE
ELSE
SET LIBRARY TO vfp2c32.fll ADDITIVE
ENDIF

LOCAL lnCon, lValue, lnRet, laInfo[1]

lcConStr   = "Driver={SQL Server Native Client 11.0};Server=server2;Database=xxxx;Uid=xxx;Pwd=xxxx;"
lnCon = SQLSTRINGCONNECT(m.lcConStr,.F.)
IF lnCon = -1
	AERROR(laError)
	DISPLAY MEMORY LIKE laError
	RETURN
ENDIF

lnRet = SQLEXECEX(lnCon, "SELECT firma FROM adresy where firma like 'A%'", 'cAdresy', 'laInfo')
* No problem
?lnRet
IF lnRet = -1
	AERROREX('laError')
	DISPLAY MEMORY LIKE laError
ENDIF

SELECT cAdresy 
BROWSE 

lnRet = SQLEXECEX(lnCon, "SELECT firma FROM adresy where firma like 'B%'", 'cAdresy', 'laInfo', SQLEXECEX_REUSE_CURSOR)
*----- ERROR 
* 2028
*  API call caused an exception.
*-----

?lnRet
IF lnRet = -1
	AERROREX('laError')
	DISPLAY MEMORY LIKE laError
ENDIF

SELECT cAdresy 
BROWSE 

SQLDISCONNECT(lnCon)
RETURN
`

The second call of the sqlExecEx function with the flag SQLEXECEX_REUSE_CURSOR causes messagebox with "API call caused an exception.".
What can I do about it?¨
Thank You.

Zdenek

**Comment by myearwood1** [comment]
I get the same error you reported. 

If you are using normal FoxPro SQLExec the existing cursor is closed and re-opened. I know that might be bad for a grid.  Andy Kramek made the "Safe Select" process. You would run the first query. Then you run the second query to a new temporary cursor. Then you zap the first cursor. Then you append from the temp cursor.

Yes, it would be great to have that happen in one go, and I'll be watching for this to get fixed.

**Comment by ChristianEhlscheid** [comment]
Hello Zdenek,

I have corrected some bugs in SqlExecEx and made some other enhancements to the function, please check the new release 2.0.0.35.

**Comment by zdenekkrejci** [comment]
Hello Christian,
it works now without problem.
Thank you very much for the perfect support.

Zdenek
