### ISSUE TITLE
ADirEx VFP SET PATH

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#26]
Hi Christian!

I noticed SetFileTimes uses the usual VFP search path.

I would very much appreciate the ability to use ADirEx to scan the VFP search path for a given filespec. 

ADDBS(SET("PATH")) , "*.frx"

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

first of all thank you for your donation.

SetFileTimes uses the VFP function FULLPATH to resolve the path of the passed filename.
In ADirEx I cannot do this, but you can easily code a wrapper around AdirEx like this:

LOCAL lcSearchPath, lcPath, lnPathCount, lnCount, xj
m.lcSearchPath = SET('PATH')
m.lnPathCount = GETWORDCOUNT(m.lcSearchPath, ';')
m.lnCount = 0
FOR m.xj = 1 TO m.lnPathCount
m.lcPath = ADDBS(GETWORDNUM(m.lcSearchPath, m.xj, ';'))
m.lnCount = m.lnCount + ADIREX('cFiles', m.lcPath + "*.prg", 0, ADIREX_DEST_CURSOR + ADIREX_FULLPATH)
ENDFOR

**Comment by myearwood1** [comment]
I could not think of an easy way for you to do it either. I would do that very similarly. I use arrays in such cases. I fix the ";" to chr(13), then make an array with alines, then addbs inside the adirex call.

```
LOCAL  lnCount, xj, laPaths[1]
m.lnCount = 0
FOR m.xj = 1 TO ALINES(laPaths, strtran(SET("Default") + SYS(2003) + ';' + SET('Path'),';',chr(13))
	m.lnCount = m.lnCount + ADIREX('cFiles', addbs(laPaths[m.xj]) + "*.prg", 0, ADIREX_DEST_CURSOR + ADIREX_FULLPATH)
ENDFOR
```

I will add it as a feature of my DirX. Together, you and I are making a very powerful DIR extension. We never got VFP6 and Sourcesafe to work together on Windows 10. I check out files to my virtual Windows 7 dev environment, but then use DirX to compare those files against my Windows 10 physical desktop. Then I can debug both environments. So I have a micro "branch" and "merge" ability.
