### ISSUE TITLE
Libcurl calling convention

### ISSUE THREAD

**Issue by GeorgiouJohn** [ChristianEhlscheid/vfp2c32#27]
Hi Christian 
I'm John from Greece.

I believe after version [2.0.0.19] the CreateCallbackFunc with nFlags = CALLBACK_CDECL has been broken. I use this for Libcurl. The current version raises an error "Declare DLL call caused an exception" at curl_easy_perform(nHandle). Older versions work ok with CALLBACK_CDECL. I run some tests and I saw that the callback function runs once and then raise the exception. Tell me if you want more informations. 

Thanks for your time.

**Comment by ChristianEhlscheid** [comment]
Hello John,

I have downloaded the library from https://github.com/calloatti/LIBCURL,
but this project only contains the actuall api wrappers and no example code.

Please provide a small snippet of VFP code to reproduce the issue, then I will have a look into it and try to fix it.

**Comment by GeorgiouJohn** [comment]
I test it. It is ok.
Thanks!
