### ISSUE TITLE
CopyFileEx returns numeric contrary to documentation

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#30]
Hi Christian

I was using SHCopyFiles to copy one file which was a mistake on my part. I switched to CopyFileEx and got an error because I expected a logical return per the docs. It returned 0. SHCopyFiles also returns a numeric. Your call. :)

Thanks for your great work.

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

thank you for your feedback.
I have fixed the documentation, which was out of date.
