### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by CHamlinPNP** [ChristianEhlscheid/vfp2c32#31]
I was looking at the repository for [2.0.0.41](https://github.com/ChristianEhlscheid/vfp2c32/commit/7b5a31831210c632b2d23459dfda878a42c9197c) posted last week. The vfp2c64.fll appears to be missing. Also, occasionally when trying to use vfp2c32.fll it comes back as invalid. When this occurs something is deleting the file. Any clues?

**Comment by ChristianEhlscheid** [comment]
Hello,
i've downloaded the latest release, i don't see any files missing.

"Also, occasionally when trying to use vfp2c32.fll it comes back as invalid. 
When this occurs something is deleting the file. Any clues?"

I can only guess, may be:
- Antivirus application malfunction
- some dependent dll file is missing - you can check this with https://github.com/lucasg/Dependencies

**Comment by CHamlinPNP** [comment]
I could not even find the file VFP2C64.fll within the repository when I did a search on-line. I will take a look at it again today.


[A person wearing glasses and looking at the camera  Description automatically generated]
Curt J Hamlin

President ▪︎ P&NP Computer Services, Inc.
[A close up of a sign  Description automatically generated]
[cid:a641676f-d945-49b1-aed4-54d1656878c1]   (585) 637-3240    [cid:e2397c53-8f68-45af-9c42-e707bbaee1a8]   (866) 670-2234
***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>  992 West Ave, Brockport, NY ***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>
[cid:ff8b673d-cf0c-4211-87b5-d1243c8ebb46]<http://www.pnpcomputer.com/>  www.pnpcomputer.com<http://www.pnpcomputer.com/>
Over 35 years of writing software for Long Term Care

CONFIDENTIALITY NOTICE: This email communication may contain private, confidential, or legally privileged information intended for the sole use of the designated and/or duly authorized recipient(s). If you are not the intended recipient or have received this email in error, please notify the sender immediately by email and permanently delete all copies of this email including all attachments without reading them. If you are the intended recipient, secure the contents in a manner that conforms to all applicable state and/or federal requirements related to privacy and confidentiality of such information.


________________________________

**Comment by CHamlinPNP** [comment]
I just checked it again. VFP2C64.DLL is not in the repository and the only location of VFP2C32.DLL is VFP2C32Help\LibCurl. I have attached the two screen shots. This has nothing to do with any kind of conflict with anything locally...this is just using the on-line search for the file.

I tried using the one in the LibCurl and it still complains (occasionally) that it is not valid and it gets deleted. It is really strange.
![2023-09-21_10-02-24](https://github.com/ChristianEhlscheid/vfp2c32/assets/34104227/7a3df68c-268d-481a-8210-959ab94fafbc)
![2023-09-21_10-03-00](https://github.com/ChristianEhlscheid/vfp2c32/assets/34104227/0fb3811f-12b2-4e3f-8b12-49f7981b9763)

**Comment by CHamlinPNP** [comment]
Just wondering if you had a chance to review what I sent to you the other day?

**Comment by calloatti** [comment]
Check releases; https://github.com/ChristianEhlscheid/vfp2c32/releases

**Comment by CHamlinPNP** [comment]
That does appear to be complete...the repository itself does not have the files as I have stated.

**Comment by myearwood1** [comment]
I just downloaded vfp2c32.zip from https://github.com/ChristianEhlscheid/vfp2c32/releases assets. It does have the vfp2c64.fll.

**Comment by myearwood1** [comment]
I get the files by clicking on the Latest button on the far left near the bottom of the following image.

![image](https://github.com/ChristianEhlscheid/vfp2c32/assets/5750619/c4cfeea8-4f99-4c8b-8cfb-847c7b72503e)

Are you referring to something else?

**Comment by CHamlinPNP** [comment]
If you look at the screen shots that I sent you. You will see that when I search for vfp2c64...nothing was found. And when I searched for vfp2c32...it only found the file in libcurl.


[A person wearing glasses and looking at the camera  Description automatically generated]
Curt J Hamlin

President ▪︎ P&NP Computer Services, Inc.
[A close up of a sign  Description automatically generated]
[cid:5c0db41c-baed-43e4-aca3-1955a428d9f4]   (585) 637-3240    [cid:888f369c-112d-4578-ba34-677b4ab98ef6]   (866) 670-2234
***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>  992 West Ave, Brockport, NY ***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>
[cid:8c5adaf3-d904-40f2-bde1-3d1d954344c6]<http://www.pnpcomputer.com/>  www.pnpcomputer.com<http://www.pnpcomputer.com/>
Over 35 years of writing software for Long Term Care

CONFIDENTIALITY NOTICE: This email communication may contain private, confidential, or legally privileged information intended for the sole use of the designated and/or duly authorized recipient(s). If you are not the intended recipient or have received this email in error, please notify the sender immediately by email and permanently delete all copies of this email including all attachments without reading them. If you are the intended recipient, secure the contents in a manner that conforms to all applicable state and/or federal requirements related to privacy and confidentiality of such information.


________________________________

**Comment by myearwood1** [comment]
Then something else is the problem. Delete any and all vfp2c32.zip on your computer. Download from GitHub again. Maybe your zip is readonly or being scanned by an anti-virus, so it prevents you from getting the latest.

OR you are not downloading the latest files in the same way that I am

OR you are talking about "respoitory" and somehow that is not the same as clicking the Latest button I showed in my screenshot.

I am not accusing you of lying, so proving your statement is not necessary.

**Comment by CHamlinPNP** [comment]
You continue to miss the point...I am looking and querying this ONLY on-line. It has nothing to do with cloning your repository or downloading it or anything else. If you use the search as I showed in the screen shots of YOUR repository...the files are not there.

Look at the screenshots that I already sent you.


[A person wearing glasses and looking at the camera  Description automatically generated]
Curt J Hamlin

President ▪︎ P&NP Computer Services, Inc.
[A close up of a sign  Description automatically generated]
[cid:6db4d9ec-7761-49c6-a179-7e51db1e4dda]   (585) 637-3240    [cid:a299fefe-e95b-40fa-973e-c7d5db5e7613]   (866) 670-2234
***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>  992 West Ave, Brockport, NY ***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>
[cid:33d6684a-ea5b-4d13-a849-f804862f0276]<http://www.pnpcomputer.com/>  www.pnpcomputer.com<http://www.pnpcomputer.com/>
Over 35 years of writing software for Long Term Care

CONFIDENTIALITY NOTICE: This email communication may contain private, confidential, or legally privileged information intended for the sole use of the designated and/or duly authorized recipient(s). If you are not the intended recipient or have received this email in error, please notify the sender immediately by email and permanently delete all copies of this email including all attachments without reading them. If you are the intended recipient, secure the contents in a manner that conforms to all applicable state and/or federal requirements related to privacy and confidentiality of such information.


________________________________

**Comment by myearwood1** [comment]
You are missing the point. What value is there in finding the files only
online when you must download them to use them which works.

**Comment by CHamlinPNP** [comment]
If you cannot even query for the files on-line...then the files will certainly not download. They do not exist in the repository as the screen shots show.


[A person wearing glasses and looking at the camera  Description automatically generated]
Curt J Hamlin

President ▪︎ P&NP Computer Services, Inc.
[A close up of a sign  Description automatically generated]
[cid:dd90a2f9-77f4-486b-83e8-f9d1c0da4470]   (585) 637-3240    [cid:515b21e5-109e-43b0-b245-edeb2e5933e8]   (866) 670-2234
***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>  992 West Ave, Brockport, NY ***@***.***,-77.985935,17z/data=!3m1!4b1!4m5!3m4!1s0x89d40171949b6219:0x7924a82b1d010a8b!8m2!3d43.2200517!4d-77.9837463>
[cid:72147e79-db16-4d58-9aa2-f5a9e4e7e32b]<http://www.pnpcomputer.com/>  www.pnpcomputer.com<http://www.pnpcomputer.com/>
Over 35 years of writing software for Long Term Care

CONFIDENTIALITY NOTICE: This email communication may contain private, confidential, or legally privileged information intended for the sole use of the designated and/or duly authorized recipient(s). If you are not the intended recipient or have received this email in error, please notify the sender immediately by email and permanently delete all copies of this email including all attachments without reading them. If you are the intended recipient, secure the contents in a manner that conforms to all applicable state and/or federal requirements related to privacy and confidentiality of such information.


________________________________

**Comment by myearwood1** [comment]
I did not query the files online, but I definitely got them when I
downloaded. Downloading is the entire purpose of GitHub. Nothing is
executed by it. If it happens to have a bug in its search of the files,
that is not preventing you from using the properly downloaded content,
which I was able to do, unless you're calling me a liar.

**Comment by myearwood1** [comment]
You are assuming the online search is searching the files that get downloaded. That may not be the case. If you get the files by downloading, then don't bother Christian with having to ensure the repository search works too.

**Comment by CHamlinPNP** [comment]
In this particular case however it did match what was being downloaded...file for file. VFP2C64 was not in there and VFP2C32 was only in the libcurl folder.

**Comment by myearwood1** [comment]
Yes, for me it downloaded fine. Systems everywhere are glitchy. So you still have not received vfp2c64? Are you sure you're clearing your browser cache and removing all local copies of the zip?

**Comment by myearwood1** [comment]
I just downloaded it again from the code page, by hitting the latest button and clicking the vfp2c32.zip under the assets section. I let it use vfp2c32 (2) as the folder name. Then I extracted the files from the zip. Then I used windows to search for *64* and got the following:

![image](https://github.com/ChristianEhlscheid/vfp2c32/assets/5750619/b1a88122-942d-4bc7-85f0-c84844832891)

**Comment by CHamlinPNP** [comment]
When you query...it does not look at latest release. It looks in the repository. This whole time I have been talking about the repository and not the "latest release".

**Comment by myearwood1** [comment]
I see, but again, the repository may not be looking at the latest content. That is awkward, but not important as only the downloaded files are necessary for use in our systems.

**Comment by CHamlinPNP** [comment]
If you download or clone the repository...you will see that what I have been saying AND THE search are accurate.

**Comment by myearwood1** [comment]
Why should I bother, when I get the latest and get the files? If Christian needs to do something to update the repository AND prepare the files for download, then I choose the download option, since that is the only absolutely necessary part. The repository is nice but not essential. If he can do both at once, fine. I don't need the repository to function as long as I get the files.

**Comment by ChristianEhlscheid** [comment]
Hello,

I was sick and staying in the hospital the last weeks.
I intentionally removed the binary fll's from the repository, so they don't clutter the commit logs.
The repository now only contains the source code, as in most repositories, and the lastest binaries are 
available in the "Releases" section.

**Comment by myearwood1** [comment]
Sorry to hear of your illness. I hope it is nothing serious. Thanks for clarifying the repository matter. I am all for reducing your workload so you can deliver more important improvements.

**Comment by myearwood1** [comment]
This issue should be closed.
