### ISSUE TITLE
IDEA: Have SHCopyFiles, SHDeleteFiles and SHMoveFiles operate on a cursor

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#32]
Given a cursor like the one produced by ADirEx, could you have SHCopyFiles, SHDeleteFiles and SHMoveFiles process the files in the specified cursor with a progress bar for the set? I certainly can do it in FoxPro code, but as I have said for years, FoxPro has cursors and a rich language to deal with them, far more easily than arrays. Once could use ADirEx to get all files in the current folder and subfolders into a cursor. Then select * from thatcursor into anothercursor where JUSTEXT(fullname)="TMP". Then SHDeleteFiles('AnotherCursor').

I have modified my DirX to scan the VFP search path as we discussed, so I could erase tmp files throughout my Search path, without scanning the entire array (in VFP6).

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

all three functions accept multiple wildcard strings as their inputs.
To delete all "tmp" files in the VFP Path environment you can use:

```
LOCAL  lcFiles, xj, laPaths[1]
lcFiles = ADDBS(SET("Default") + SYS(2003)) + "*.tmp"
FOR m.xj = 1 TO ALINES(laPaths, strtran(';' + SET('Path'),';',chr(13))
	m.lcFiles = m.lcFiles + CHR(0) + ADDBS(laPaths[m.xj]) + "*.tmp"
ENDFOR
SHDeleteFiles(m.lcFiles)

```
This should also be far more efficient than to first enumerate the files and then pass each file individually to the function.

If you need more then the simple wildcard filtering by file extension you can build a file list by using

```
m.lcFiles = ''
ADIREX(...)
SELECT cursorname
SCAN
 m.lcFiles = m.lcFiles + IIF(EMPTY(m.lcFiles),'',CHR(0)) + cursorname.fullname
ENDSCAN
SHCopyFiles(m.lcFiles)
```

I think this is better done in VFP code.
Regards
Christian

**Comment by myearwood1** [comment]
I accept your answer. Just to clarify, I used .tmp as an example. I already have a cursor of files to process, and since Fox has long made the mistake of not using cursors it seems obvious to me to add cursor support. :)
