### ISSUE TITLE
MoveFileEx and CopyFileEx, but not DeleteFileEx

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#34]
Hi Christian

I have been wondering. DeleteFileEx cannot always delete a file, can it? If the file is open exclusive by another user, DeleteFileEx should error out.

Obviously there is little point to having a CallBack, but a return value that indicates Progress_Continue or Progress_Cancel should be returned no matter the function?

What do you think?

Thanks

**Comment by ChristianEhlscheid** [comment]
Hello Mike,

yes, you're right. But DeleteFileEx throws an error when it can't delete the file because it is currently opened by another process,
the function behaves like the FoxPro DELETE FILE command, the only difference is that it will remove the "readonly" file attribute if neccessary which also prevents deletion.

**Comment by myearwood1** [comment]
Hi Christian

Is it impossible for this function to do both? I am in VFP6. I don't have try catch. I would love to just ask the function if it deleted the file.

By the way, can you write up how to build the fll? I would like to be able to help you if you are overwhelmed. I have not done c++ in over a decade now, but I will take a refresher course.

**Comment by ChristianEhlscheid** [comment]
Hello,

sure, I'll implement that, it's a small change.
Unfortunaltly I've done so many changes locally (new functions and extended SqlExecEx heavily) that it will take a while 
until the next release.

**Comment by myearwood1** [comment]
Not a problem for me. I would be honored to learn from you to be able to assist when you need help.

**Comment by myearwood1** [comment]
When I run the following code, DeleteFileEx does not return .T. or .F. when the error happens. 

```
ON ERROR
set step on

close all
x=fcreate(addbs(sys(2023))+"test1.txt")
y=fcreate(addbs(sys(2023))+"test2.txt")
z=fcreate(addbs(sys(2023))+"test3.txt")
fclose(m.x)
*fclose(m.y)
fclose(m.z)

create cursor c_Temp (filename c(254))
insert into c_Temp (filename) values (addbs(sys(2023))+"test1.txt")
insert into c_temp (filename) values (addbs(sys(2023))+"test2.txt")
insert into c_temp (filename) values (addbs(sys(2023))+"test3.txt")

local lcOnError, lcErrorMessage
lcOnError = on("error")
ON ERROR lcErrorMessage = message()
select c_temp
m.lcErrorMessage = ""
scan for m.lcErrorMessage == ""
	?DeleteFileEx(alltrim(filename))
	IF NOT m.lcErrorMessage == ""
		?alltrim(c_temp.filename) + " " + m.lcErrorMessage
		m.lcErrorMessage = ""
	ENDIF
endscan
on error &lcOnError.
use in (select("c_temp"))
```
I'd like the loop to look like this:
```
local lcOnError, lcErrorMessage
lcOnError = on("error")
ON ERROR lcErrorMessage = message()
select c_temp
scan for NOT DeleteFileEx(alltrim(filename))
	?alltrim(c_temp.filename) + " " + m.lcErrorMessage
endscan
on error &lcOnError.
use in (select("c_temp"))
```
If there was a way to tell DeleteFileEx not to output any error message, I could use AErrorEx to check for an error without using ON ERROR.

```
scan for NOT DeleteFileEx(alltrim(filename),"QUIET")
	if AErrorEx('laError')>0
		?alltrim(c_temp.filename) + " " + laError[3]
	endif
endscan

```

**Comment by myearwood1** [comment]
I just discovered that I can use llDeleted=(TYPE("DeleteFileEx(filename)")="U") as an indication that the delete worked or not and it does not trigger an ON ERROR. That works, but it's pretty ugly.

Please add a QUIET switch to DeleteFileEx and allow it to return .F. during an error. At the least, I can then `DeleteFileEx(filename,'QUIET')` if I don't care if the file gets deleted or not and I won't have to remember and reset ON ERROR. If I do want to see why the delete failed I can use AErrorEx. Otherwise, without the quiet switch our application errorhandler will catch it.

If we want to delete a file and not trigger the application errorhandler, we'd turn on quiet mode. We have multiple copies of the application running,  so temporary files are open when we try to delete.

**Comment by myearwood1** [comment]
Hello Christian
When you get a chance, please add 2 new parameters. These 2 new parameters are completely optional to your users. For a delete function many will say this is overkill, but ....

1 Add a second logical parameter for quiet mode, so DeleteFileEx can operate without raising ON ERROR. It may be a file must be deleted and we want to know when it is not, so we would set quiet mode off or don't pass it.

2 Add a third parameter, 1 returns the text of the error message, 2 returns the error number. Otherwise just return .T. or .F. 
If the named file is not found, return ""/0/.T.

If the quiet flag is .F., and the third parameter is given, raise either the error number or the error text.

What this permits is an SQL command of this type. c_Temp contains a list of .tmp files. 

select ;
	padr(DeleteFileEx(alltrim(filename),.T.,1),120) as DeleteMessage ;
	from c_Temp ;
	having NOT alltrim(DeleteMessage)=='' ;
	into cursor c_CouldNotDelete

That SQL will delete files, store the error message and the developer can decide how to react. It does it without looping.

**Comment by myearwood1** [comment]
SQL executes the DeleteFileEx once before running the query. So, if the file exists, it will be deleted, and then DeleteFileEx will attempt to delete the file again, so returning ""/0/.T. when the file is not found serves a second purpose.
I did it in FoxPro, hoping you can be motivated to do it in your DeleteFileEx.

```
LPARAMETERS m.tcFileName, m.tlQuiet, m.tnReturn

* This is a true DeleteFile function. 
* DeleteFileEx removes the readonly flag.
* Usage: 
* 1 Delete the named file and do not raise any error
* lcDeleted = DeleteFileExTemp('_76576.tmp',.T.,1)
* 2 Delete the named file and let the ErrorHandler intercept
* lcDeleted = DeleteFileExTemp('_76576.tmp',1)
* 3 Delete the named file and react to error condition
* lcDeleted = DeleteFileExTemp('_76576.tmp',.t.,1)
* IF NOT EMPTY(m.lcDeleted)
* 	ERROR m.lcDeleted
* ENDCASE
* 4 Additionally, this can be used as such:
* select 
*	DeleteFileExTemp(table.filename,.T.,1) as DeleteMessage 
*	from table 
*	having !alltrim(DeleteMessage) == '' 
*	into cursor c_NotDeleted
*
* Then we can either investigate or ignore.
* luDeleted is set to ''/0/.T. on success else an error message/error number/.F.

*tnReturn 
*	not passed, .T. or .F. is returned
*	set to 1 - the error message text is returned
*	set to 2 - the error number is returned
*
* Unlike the FoxPro DELETE FILE COMMMAND this indicates if the file was deleted or not.
* If not, we can choose to determine why or ignore it.

* If m.tlQuiet is .T., the error will still be returned, but not raised.

LOCAL lcReturn, llReturn, lnReturn, laDeleted[1,1]
lcReturn = ""
llReturn = .F.
lnReturn = 0
do while .t.
	IF EMPTY(m.tcFileName)
		lcReturn = "No file passed."
		lnReturn = -1
		EXIT
	ENDIF
	if not file(m.tcFileName)
		*If the file is not found, pretend it was deleted.
		llReturn = .T.
		EXIT
	endif
	IF NOT vfp2c32()
		lcReturn = "vfp2c32 could not load."
		lnReturn = -2
		EXIT
	ENDIF
	llReturn = (TYPE("DeleteFileEx(filename)")<>"U") 
	if NOT m.llReturn
		IF AErrorEx('laDeleted')>0
			lcReturn = laDeleted[1,3]
			lnReturn = laDeleted[1,1]
			if NOT m.tlQuiet
				if pcount()=3 and m.tnReturn = 1
					error m.lcReturn
				else
					error m.lnReturn
				endif
			endif
		else
			lcReturn = "unknown"
			lnReturn = -3
		ENDIF
	endif
	exit
enddo
return iif(pcount()=3,iif(m.tnReturn = 1,m.lcReturn,m.lnReturn),m.llReturn)

```

I would then have my DeleteFileEx.prg defer to yours. :)

**Comment by ChristianEhlscheid** [comment]
Hello Mike,
thank you for the ongoing suggestions to improve the library.
I've had other obligations and problems in the last months, but I've made some major improvements to SQLExecEx,
implemented a dozen other ODBC related functions, enhanced the SHCopyFiles, SHMoveFiles, SHDeleteFiles and DeleteFileEx.
I have to document all this, but a new version should be available in the coming weeks.

**Comment by myearwood1** [comment]
I am helping the GoFish project speed up by calling your routines.
