### ISSUE TITLE
ADirEx > SHDeleteFiles crash because of memo field

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#35]
Hi Christian

I am using ADirEx to create a cursor of files to be deleted. The fully qualified path is in a memo field in the cursor. SHDeleteFiles gave me a data type mismatch on the fullname. I had to alltrim to get it to work.

I expected it to accept the memo field.

Do you agree?

Thanks

Mike

**Comment by ChristianEhlscheid** [comment]
Hello Mike,
yes, this will be fixed in the next version.
Thank you for the report.
