### ISSUE TITLE
CreateThreadObject.AbortCall doesn't work in some situations

### ISSUE THREAD

**Issue by wisewebpt** [ChristianEhlscheid/vfp2c32#38]
Hi,

For example, if you have a function that calls the function file with a UNC path that does't exist, (FILE("\\192.168.2.222\whatever\whatever.wtv")), AbortCall returns true, but the function keeps running to completion.
Anyway to force the function to always stop?
Alternatively, if that proves impossible, maybe a way to just kill (for sure) the thread?

Thanks.

**Comment by wisewebpt** [comment]
Managed to work around it using OpenThread and TerminateThread, but I'm not sure if everything is getting cleaned up.

**Comment by ChristianEhlscheid** [comment]
Hello,
thread abortion works be setting a windows event object,
so it only works by regulary checking the object or when you pass it on to some api function e.g. WaitForMultipleObjects.
For your particular situation you would have to use the "CreateFile" api function to check for the file existance asynchronously.
In the "vfpsrvhost" example project, there is some code which has the "abort" functionality implemented, you might have a look at that.
Using OpenThread and TerminateThread is not a good way to solve that problem, it might lead to memory leaks or undefined behaviour.

**Comment by wisewebpt** [comment]
Thanks
