### ISSUE TITLE
New function ISvfp2c32

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#40]
Hi Christian!

I tend not to load a library and then access its components. Instead, I create a set of small programs that each attempt to load the FLL and defer to the required component. For example, DeleteFileEx.prg attempts to set library to vfp2c32.fll and then calls your DeleteFileEx.

DeleteFileEx.PRG
LPARAMETERS tcFileName
IF NOT vfp2c32() && this checks if vfp2c32.fll is in set library.
	RETURN .F.
ENDIF
RETURN DeleteFileEx(m.tcFileName)

In this way, I only have to call upon your specific function by name. If your fll is not loaded, it will load and then your function takes over.

The first time DeleteFileEx.PRG fires, it runs vfp2c32.prg. It would be really nice if you had a vfp2c32 function. That would save my programs from even checking if the FLL is loaded.

I have str2double.prg
LPARAMETERS tcBuffer
IF NOT vfp2c32()
    RETURN .F.
ENDIF
return str2double(m.tcBuffer)

If vfp2c32.fll had a function called ISvfp2c32 that ONLY returns .T., the first of my little programs would check for and load your FLL, but none of the others would. However, if somewhere in my program, your library was released, then it would automatically be reloaded by the next load-and-defer program and then none of the others would reload it.

This has to be the smallest function anyone ever asked of you. :)

Mike

**Comment by calloatti** [comment]
No need to do this if you use a prg with the same name as a function in the fll.

fll and dll functions have priority over prgs with the same name, so just call the function, if the fll is not loaded the prg will be called, load the fll there and return the value of the function. next time, the fll function will be called.

Example:

```
*!* osex.prg

set library to vfp2c32.fll additive

return osex()
```

Example for dll declares, not related to vfp2c32, just a generic example:

```
*!* _apiBeep.prg

Lparameters dwFreq, dwDuration

Declare Integer Beep In WIN32API As _apiBeep ;
  Integer dwFreq, ;
  Integer dwDuration

Return _apiBeep(m.dwFreq, m.dwDuration)
```

**Comment by myearwood1** [comment]
You missed the point of my request. I already do what you show and have been since Drew Speedie himself showed me while I worked with him. I showed that I know how to do it in my example. 

Your second example with the alias is interesting. That may come in handy.

I do not want to issue set library additive if the fll has already been loaded.

My isvfp2c32.prg uses x2setlib to determine if the library is loaded, 1000 x2setlib.prg calls take .017 seconds, but 1000 set library additive takes 0.478 seconds. That is much more than a 12 percent savings. Professor Donald Knuth was right when he said programmers foolishly dismiss even 12 percent gains, which all other engineering disciplines would gladly accept when so easily gained.

I also do not want each of these little programs to have the name of the fll hardcoded in them. isvfp2c32.prg gives me a single place to name the fll.

**Comment by myearwood1** [comment]
Additionally, my isvfp2c32.prg takes .177 seconds and set library additive still takes .482. I am eager to see how Christian's isvfp2c32 function would compare.

**Comment by myearwood1** [comment]
The alias applies to the entire FLL? That is of very little use to me. I would far prefer to have a collection of DLLs instead of one FLL.

**Comment by myearwood1** [comment]
It would also be nice to have a vfp2c32 function that only returns .F.
That way, I can have my vfp2c32 function load the FLL, and subsequent calls to vfp2c32 in my FoxPro app, will correctly show that the FLL was loaded before the current call.

```
*Was vfp2c32 loaded here?
local llLoaded
llLoaded = VFP2C32()
if DirX(c_Temp,sys(2023)+"*.t,mp")>0
	select padr(DeleteFileExTemp(alltrim(filename),.T.,1),120) as DeletedMessage ;
		from c_Temp ;
		having not alltrim(DeletedMessage)==''  ; 
		into cursor c_NotDeleted nofilter
	use in (select(m.lcNotDeletedCursor))
ENDIF
*If so, release it.
ReleaseVFP2C32(m.llLoaded)
```

**Comment by ChristianEhlscheid** [comment]
I will add the requested VFP2C32 function.
Shouldn't it return .T. though?

**Comment by ChristianEhlscheid** [comment]
Sorry, i was confused, now i get the logic behind it ...

**Comment by myearwood1** [comment]
No sir. I want the first call to my .prg to return .t. since it loads it.
Yours should return false since it never loads your library.

**Comment by myearwood1** [comment]
You are an excellent developer. I knew you would get it.
