### ISSUE TITLE
Function naming and parameter conflicts

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#42]
Suppose I have SetFileAttributes.prg that does the following:
```
LPARAMETERS m.lpFileName, m.dwFileAttributes
DECLARE INTEGER SetFileAttributes IN kernel32 STRING lpFileName, INTEGER dwFileAttributes
RETURN SetFileAttributes(@lpFileName, @dwFileAttributes)
```
Then I set library to vfp2c32. You also have a setfileattributes. The DLL takes precedence. Your setfileattibutes has a third optional parameter, but if I pass the third parameter to setfileattributes, I always get the error Too Many Arguments. This is something to be aware of.

Here's a bit of my LIST STATUS TO STAT.TXT

API library                           Instance Handle
c:\...\progs\vfp2c32.fll              268435456

    Function                          Address
    SetFileAttributes                 10023B70    
    SetFileAttributesEx               10023A00    

Declared DLLs:
GetIDispatch                                        c:\cj_sa_common\progs\vfp2c32.fll
SetFileAttributes                                   c:\windows\system32\kernel32.dll

Now we go a little farther. Having loaded vfp2c32, but not declared GetFileAttributes from the Windows API, my GetFileAttributes.prg proxy loader cannot fire as your GetFileAttributes exists and does not return the same values as the Windows API and my app crashes. Ouch.

I am testing this because Doug Hennig mentioned possible conflicts. I doubt many are using your SetFileAttributes if they know of the windows API. 

I think if you're wrapping a windows API call with a function of the same name, you cannot change the parameters or the return data type. You'd have to assume the user has the windows API, much as you assume ADir exists so you made ADirEX and rightly so.

**Comment by ChristianEhlscheid** [comment]
Hello Mike, 
yes this is an issue I haven't considered thouroughly.
Now there are two options to resolve this issue,
-leave it as it is, if one wants to use the windows api you can still by using DECLARE .. AS ..., aliasing the api function 
-rename the conflicting functions in VFP2C32, which breaks backwards compatibility with older version of the library

Both options have their drawbacks, I tend to do the latter.

**Comment by myearwood1** [comment]
Just so we're clear - I too tend to do the latter - rename things so they are better going forward.

We had to create a Config.fpw file if it did not exist OR it exists but is younger than a file on the server. Those conditions can be reduced to checking the datetimes of 2 files. If the config.fpw does not exist, the datetime can be zero. If the remote file exists, it has a datetime. If it does not exist and the config.fpw does not exist, don't create it.

So If there is a remote file and no local, create the local. If there is a remote file and it's newer than the local, create the local.

Respecting your stated purpose for vfp2c32, that being to give FoxPro programmers access to the API without having to learn too much C++ I made this:

GetFileLastModified.prg
```
LPARAMETERS tcFileName
RETURN GetFileLastTime(m.tcFileName,3)
```
The Windows API - GetFileTime - is rather ugly and overloaded. However, using the GetFileTime API - you could make GetFileLastModified and its siblings and we Fox programmers would gain three very nice modules from you. Of course, I'd rather my little functions just defer to yours. :)

GetFileLastTime.prg encapsulates the details of the GetFileTimes API
```
LPARAMETERS tcFileName,tnFlag
LOCAL lnHandle, lnReturn
lnReturn = 0
*Even if the file is open, this will get the datetime.
lnHandle = CreateFile(m.tcFileName, 0, 0, 0, 3, 0, 0)
IF EVAL('GetFileTime(m.lnHandle,' + substr("@lnReturn,0,0~0,@lnReturn,0~0,0,@lnReturn~",(m.tnFlag-1)*14+1,13) + ')')=1
	*
ENDIF
CloseHandle(m.lnHandle)
RETURN m.lnReturn
```

**Comment by ChristianEhlscheid** [comment]
Hello,
I will rename the functions.

You might have overlooked it, but there already is a "GetFileTimes" function in the fll.

**Comment by myearwood1** [comment]
I did overlook it. Thanks for pointing it out. Yours may have to be renamed too.
It is a bit confusing, but Windows API is GetFileTime and yours is GetFileTimes (with the s). That can probably remain unchanged.

**Comment by ChristianEhlscheid** [comment]
Hello Mike,
just wanted to inform you that the new version is now available.

**Comment by myearwood1** [comment]
Fantastic! I will try it soon.
