### ISSUE TITLE
SQLExecEx error

### ISSUE THREAD

**Issue by esreed** [ChristianEhlscheid/vfp2c32#5]
Hi Christian.
I've updated **vfp2c32t.fll** with the **latest version** and now I'm getting an error "_Invalid cursor schema for field 'captotal': length 20_" when I try to run **SqlExecEx function** with a Select command **that works as expected in an older version**.
The 'captotal' is a double precision field from a table called 'cadsocios' in a PostgreSQL database.
In this table there are 4 records with the following values for the 'captotal' field:
1- 0
2- 100
3- 0
4- 0
I hope that this can give you a clue about what's going on.
If you need more details, feel free to contact me.
Thanks a lot.

**Comment by ChristianEhlscheid** [comment]
Hello Emerson,

I've have added additional check's for datatype size limits to SqlExecEx in the latest version, which result in better 
error messages.

Without these checks you should have gotten just another error (VFP Error 1713 - "Field width or number of decimal places is invalid") without further information which column was problematic.

The limit for the "Numeric" datatype is N(20,19) and for "Double" it is B(18).

In Postgres you can create numeric columns with almost unlimited precision,
if you get this error that's at least a sign you have a column that can't be represented without loss of precision in VFP.

If you can live with the loss of precision, you can specifiy the column datatype manually (e.g. pass "cadsocios B(18)" as cursorschema parameter to SqlExecEx).

Regards
Christian

**Comment by esreed** [comment]
Hi Christian.
I followed your suggestion and everything is working as expected again.
Thanks for your support!
