### ISSUE TITLE
needed help to make call to GetLastInputInfo in user32

### ISSUE THREAD

**Issue by jebodu** [ChristianEhlscheid/vfp2c32#6]
Please can You look at 
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getlastinputinfo 
and parameter definition
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-lastinputinfo 

Do I need to create struct class for this kind of parameter because parameter actually is pointer to struct of lastinputinfo 
and how can I declare getlastinputinfo with integer or string passed by ref.

I used vfp2c32 UI to create fox class for lastinputinfo structure....
and tried to declare with string and long as input param, but always function returns 0 and documentation for getlastinputinfo states that non zero is success.

Can You give mi instructions how to prepare parameter and correctly declare function
or
maybe You can include this function in FLL in future releases...

Thanks
Milos

**Comment by calloatti** [comment]
You don't need vfp2c32 to do this

```
*!* returns the number of milliseconds that the system has been idle

Local nlast, nnow, plii

declare integer GetLastInputInfo in user32.dll string  @plii
declare integer GetTickCount in kernel32.dll

m.plii 	= 0h0800000000000000

GetLastInputInfo(@m.plii)

m.nlast = ctobin(right(m.plii, 4), "4rs")

m.nnow = GetTickCount()

return m.nnow - m.nlast 
```

**Comment by jebodu** [comment]
thank You very much. I didnt know how to initialize m. plii variable.





уто, 4. мај 2021. 18:41 Carlos Alloatti ***@***.***> је
написао/ла:
