### ISSUE TITLE
"Data type mismatch" when using createcallbackfunc

### ISSUE THREAD

**Issue by calloatti** [ChristianEhlscheid/vfp2c32#7]
The help file states that  for createcallbackfunc:

> oObjectRef (optional)
> If the FoxPro method should be called back on an object reference, you can pass the object reference in this parameter.
>  If you want to pass the nFlags parameter but don't want to pass an object pass NULL instead.

This:

`m.callback = createcallbackfunc('callbackfunc', 'VOID', 'INTEGER,DOUBLE,INTEGER', null, CALLBACK_ASYNCRONOUS_POST)`

fails with a "Data type mismatch" error

![image](https://user-images.githubusercontent.com/12817862/117039550-49286280-acdf-11eb-8e1d-1e0f0ca17fdc.png)

**Comment by calloatti** [comment]
Also,  could you please clarify the scope of `cCallback`?

Does it need to be a function defined as

```
Function cCallback
...
Endfunc
```

Or can it be just a ` cCallback.prg `

**Comment by ChristianEhlscheid** [comment]
Hallo Carlos,

I've uploaded a fixed version (2.0.0.19),
as you've found out yourself the "cCallbackFunc" parameter can accept a "function name" or a "procedure/file name".

Christian

**Comment by calloatti** [comment]
Thank you Christian! Trying to create a callback for https://libzip.org/documentation/zip_register_progress_callback_with_state.html but having problems. Getting a "Declare DLL call caused an exception", but it seems to work once, will probably ask for your help (if you don't mind) in a new issue if I can't make it work.

**Comment by calloatti** [comment]
It still happens with 2.0.0.19. I have made sure to delete all the old versions of vfp2c32.fll and use the new one. 

A `vfp2c32_version` function would be handy maybe

**Comment by ChristianEhlscheid** [comment]
Hello Carlos,

sorry, i've the wrong files. Now it's really updated ...

**Comment by calloatti** [comment]
Works perfect now, thanks!

And creating a callback to use in https://libzip.org/documentation/zip_register_progress_callback_with_state.html works fine now, using CALLBACK_CDECL
